apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ops-view
spec:
  rules:
  - host: "kops.k3s.dev"
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80